extends Node

var SQUARE_WIDTH = 24
var SQUARE_BORDER_WIDTH = 3
var PUZZLE_HEIGHT = 20
var PUZZLE_WIDTH = 10

var SIDEBAR_WIDTH = SQUARE_WIDTH * 6
var WAR_ZONE_WIDTH = PUZZLE_WIDTH * SQUARE_WIDTH

var CANVAS_WIDTH = SIDEBAR_WIDTH + WAR_ZONE_WIDTH
var CANVAS_HEIGHT = PUZZLE_HEIGHT * SQUARE_WIDTH

var FONT_SIZE_SMALL = 14
var FONT_SIZE_LARGE = 34

var INITIAL_FALL_RATE = 1000
var FLOOR_LOCK_RATE = 500
var FALL_RATE_REDUCTION_FACTOR = 3
var LINES_PER_LEVEL = 10

var BUTTON_PADDING_LEFT = 4
